btc_wallet/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('wallet.urls')),
    path('users/', include('users.urls')),
]

users/urls.py
"""Defines URL patterns for users"""

from django.urls import path, include

from . import views

app_name = 'users'
urlpatterns = [
    # Include default auth urls.
    path('', include('django.contrib.auth.urls')),
    # Registration page.
    path('register/', views.register, name='register'),
]

wallet/urls.py
"""Define URLS pattern for 8Trigrams  wallet"""

from django.urls import path
from . import views

app_name = 'wallet'
urlpatterns = [       
    #user dashboatd/home page
    path('', views.dashboard, name='dashboard'),
    #send page
    path('send_page', views.send_page, name='send_page'),
    #send btc
    path('send', views.send, name="send"),
]

users/models.py
from django.db import models

# Create your models here.

wallet/models.py
from django.db import models
from django.contrib.auth.models import User

class Wallet(models.Model):
    """A wallet that belongs to a user"""
    private_key=models.CharField(max_length=300)
    public_key=models.CharField(max_length=300)
    address=models.CharField(max_length=300)
    owner=models.ForeignKey(User, on_delete=models.CASCADE, related_name="owns")
    
    def  __str__(self):
        """Return a string representation of the wallet"""
        return self.owner.username
        
    
    

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

from bitcoinlib.keys import Key
from bitcoinlib.wallets import Wallet

from wallet.models import Wallet as Custom_Wallet

def register(request):
	"""Register a new user."""
	if request.method != 'POST':
		# Display blank registration form.
		form = UserCreationForm()
	else:
		# Process completed form.
		form = UserCreationForm(data=request.POST)
		
		if form.is_valid():
			#create new user
			new_user = form.save()
			
			#create new custom wallet
			new_wallet=Custom_Wallet()
			
			#create bitcoin new key
			new_key=Key()
			
			#get the new private & public keys and the new address
			private_key=new_key.private_hex
			public_key=new_key.public_hex
			address=new_key.address()
			
			#add the 3 info above to the cutsom wallet
			new_wallet.private_key=private_key
			new_wallet.public_key=public_key
			new_wallet.address=address
			new_wallet.owner=new_user
			
			#save the new wallet
			new_wallet.save()
			#create bitcoinlib wallet with user details
			Wallet.create(new_user.username, keys=private_key, scheme="single")
			
			# Log the user in and then redirect to home page.
			login(request, new_user)
			return redirect('wallet:dashboard')
	
	# Display a blank or invalid form.
	context = {'form': form}
	return render(request, 'registration/register.html', context)
		

wallet/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

from bitcoinlib.services.services import Service
from bitcoinlib.transactions import Transaction
from bitcoinlib.wallets import Wallet as Lib_wallet

from bitcoinlib.services.blockchaininfo import BlockchainInfoClient as BInfo

from .models import Wallet

def _get_tx_type(request, txid, address):
    """A helper function to determine if a tx (transaction)  is credit or debit"""
    service=Service()
    try:
        #get the tx 
        tx=service.gettransaction(txid)
        #convert the tx object to a dictionary
        dict=tx.as_dict()
        inputs=dict['inputs']
        
        for input in inputs:
            prev_txid=input['prev_txid']
            prev_t=service.gettransaction(prev_txid)
            dict2=prev_t.as_dict()
            outputs=dict2['outputs']
            for output in outputs:
                sender_address=output['address']
                break
            break
                
        if sender_address==address:
            return 'Sent'
        else:
            return 'Received'
    except AttributeError:
        #incase of coinbase tx
        return 'Received'
    
@login_required
def dashboard(request):
    """the wallet dashboard for a user"""   
    user=request.user
    wallet=Wallet.objects.filter(owner=user)
    user_wallet=wallet[0]
    address=user_wallet.address
    
    #get bitcoinlib service  and wallet bal 
    service=Service()
    wallet_balance=service.getbalance(address)/100000000
    wallet_balance=round(wallet_balance,5)#round tp 2d.p
    
    #PS- divide by 100m above  to convert sat to btc
    
    #get live btc price from api
    base_url=" "
    network="bitcoin"
    denominator='1'
    
    client=BInfo(network=network, base_url=base_url, denominator=denominator)
    
    api_url="https://blockchain.info/tobtc?currency=USD&value=35000"
    num_btc=client.compose_request(api_url)
    """the idea is to get the value of $35,000 in btc and use ratio calcs to get the value of 1 btc in $ """
    btc_price=35000/num_btc
    btc_price=round(btc_price,2)
    
    #wallet bal in $
    wallet_balance_dols= round(wallet_balance*btc_price,2)
    
    #get & process transactions for the user's wallet
    transaction_objects=service.gettransactions(address, limit=6)
    transactions=[  ]
    
    for transaction_object in transaction_objects:
        transaction_detail={ }
        
        dict=transaction_object.as_dict()
        amount=(dict['output_total'] - dict['fee'])/100_000_000
        hash=dict['txid']
        date=dict['date']
        status=dict['status']
        #pack tx details in 1 dict
        transaction_detail['type']= _get_tx_type(request,hash, address)
             
        transaction_detail['amount'] =round(amount,5)
        transaction_detail['hash']=hash
        transaction_detail['date']=date
        transaction_detail['status']=status
        
        transactions.append(transaction_detail)
        transactions.reverse()
        
                        
    context={
        "user":user,
        "user_wallet":user_wallet,
        "wallet_balance":wallet_balance,
        "btc_price":btc_price,
        'transactions':transactions,
        "wallet_balance_dols":wallet_balance_dols
    }
    
    return render(request, 'wallet/dashboard.html',context)

@login_required    
def send_page(request):
    """return the send_page"""
    return render(request, 'wallet/send_page.html')

@login_required
def send(request):
    """send btc to an address provided"""
    if request.method == 'POST':
        
        #get reciever address & amount        
        recipient_address=request.POST.get('recipient_address')
        #remove all whitespace
        recipient_address="".join(recipient_address.split())        
        amount=float(request.POST.get('amount'))
        sat_amount=amount*100_000_000
        
        #retrieve sender  name & wallet 
        user=request.user
        wallet=Lib_wallet(user.username)
        #sent btc
        wallet.send_to(recipient_address,sat_amount, offline=True)
        
        context={ 
            "amount":amount,
            "recipient_address":recipient_address
        }
                        
        return render(request, 'wallet/send_success.html', context)
        

wallet/templates/wallet/dashboard.html
{% extends "wallet/base.html" %}
{% load humanize %}
{% load static %}

{% block content %}
    <style>
        #dashboard_cont{
            background: url("{% static 'pics/blue_bg.jpg' %}") no-repeat;
        }
    </style>  
     
    <section id="dashboard_cont">
        <span id="btc_bal">{{wallet_balance}} BTC </span> <br/>
        <span id="dol_bal"> ≈${{wallet_balance_dols | intcomma}}</span>  <br/>   
        <apan id="addr" > {{user_wallet.address}} </span> 
        <br/>
        <div id="send_rec_cont">
             <a href="{% url 'wallet:send_page' %}"><div id="send_cont">
               <span id="send_text">Send <svg xmlns="http://www.w3.org/2000/svg" width="19" height="19" fill="currentColor" class="bi bi-arrow-bar-up" viewBox="0 0 14 14"><path fill-rule="evenodd" d="M8 10a.5.5 0 0 0 .5-.5V3.707l2.146 2.147a.5.5 0 0 0 .708-.708l-3-3a.5.5 0 0 0-.708 0l-3 3a.5.5 0 1 0 .708.708L7.5 3.707V9.5a.5.5 0 0 0 .5.5zm-7 2.5a.5.5 0 0 1 .5-.5h13a.5.5 0 0 1 0 1h-13a.5.5 0 0 1-.5-.5z"/></svg></span>
            </div></a>
            <a href="#"><div id="receive_cont" onclick="myFunction()">
                <span id="rec_text">Receive <svg xmlns="http://www.w3.org/2000/svg" width="19" height="19" fill="currentColor" class="bi bi-arrow-bar-down" viewBox="0 0 14 14"><path fill-rule="evenodd" d="M1 3.5a.5.5 0 0 1 .5-.5h13a.5.5 0 0 1 0 1h-13a.5.5 0 0 1-.5-.5zM8 6a.5.5 0 0 1 .5.5v5.793l2.146-2.147a.5.5 0 0 1 .708.708l-3 3a.5.5 0 0 1-.708 0l-3-3a.5.5 0 0 1 .708-.708L7.5 12.293V6.5A.5.5 0 0 1 8 6z"/></svg></span>
            </div></a>
        </div>
    </section>     
    <section id="tx_head">
         <h2> Recent Transactions :</h2>
     </section>    
    {% for transaction in transactions %}
        <a href="https://www.blockchain.com/btc/tx/{{transaction.hash}}"><section class="tx">            
            <span id="tx_detail">{{transaction.type}} {{transaction.amount}}  BTC<br/>
            {{transaction.date|timesince}} ago</span>
            <span id="hash">{{transaction.hash}}</span>
        </section></a>
    {% empty %}
        <p id="no_tx_text"> No transactions yet !!!</p>
        <br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
    {% endfor %}
    
    <section id="footer" >
        <p id="copyright">Ojeh Damian <br/> ©2022 All rights reserved</p>
        <p id="nickname">DamyKS</p>
        
        <div id="footer_icons_cont">
            <a href="mailto:damianojeh@gmail.com"><svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="black" class="bi bi-envelope" viewBox="0 0 16 16"><path d="M0 4a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V4Zm2-1a1 1 0 0 0-1 1v.217l7 4.2 7-4.2V4a1 1 0 0 0-1-1H2Zm13 2.383-4.708 2.825L15 11.105V5.383Zm-.034 6.876-5.64-3.471L8 9.583l-1.326-.795-5.64 3.47A1 1 0 0 0 2 13h12a1 1 0 0 0 .966-.741ZM1 11.105l4.708-2.897L1 5.383v5.722Z"/></svg></a>
            <a href="https://www.facebook.com/profile.php?id=100076611390670"><svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="black" class="bi bi-facebook" viewBox="0 0 16 16"><path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z"/></svg></a>
            <a href="https://wa.me/message/EL6YL43PPF3EG1" ><svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="black" class="bi bi-whatsapp" viewBox="0 0 16 16"><path d="M13.601 2.326A7.854 7.854 0 0 0 7.994 0C3.627 0 .068 3.558.064 7.926c0 1.399.366 2.76 1.057 3.965L0 16l4.204-1.102a7.933 7.933 0 0 0 3.79.965h.004c4.368 0 7.926-3.558 7.93-7.93A7.898 7.898 0 0 0 13.6 2.326zM7.994 14.521a6.573 6.573 0 0 1-3.356-.92l-.24-.144-2.494.654.666-2.433-.156-.251a6.56 6.56 0 0 1-1.007-3.505c0-3.626 2.957-6.584 6.591-6.584a6.56 6.56 0 0 1 4.66 1.931 6.557 6.557 0 0 1 1.928 4.66c-.004 3.639-2.961 6.592-6.592 6.592zm3.615-4.934c-.197-.099-1.17-.578-1.353-.646-.182-.065-.315-.099-.445.099-.133.197-.513.646-.627.775-.114.133-.232.148-.43.05-.197-.1-.836-.308-1.592-.985-.59-.525-.985-1.175-1.103-1.372-.114-.198-.011-.304.088-.403.087-.088.197-.232.296-.346.1-.114.133-.198.198-.33.065-.134.034-.248-.015-.347-.05-.099-.445-1.076-.612-1.47-.16-.389-.323-.335-.445-.34-.114-.007-.247-.007-.38-.007a.729.729 0 0 0-.529.247c-.182.198-.691.677-.691 1.654 0 .977.71 1.916.81 2.049.098.133 1.394 2.132 3.383 2.992.47.205.84.326 1.129.418.475.152.904.129 1.246.08.38-.058 1.171-.48 1.338-.943.164-.464.164-.86.114-.943-.049-.084-.182-.133-.38-.232z"/></svg></a>
            <a href="https://www.linkedin.com/in/damian-ojeh" > <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="black" class="bi bi-linkedin" viewBox="0 0 16 16"><path d="M0 1.146C0 .513.526 0 1.175 0h13.65C15.474 0 16 .513 16 1.146v13.708c0 .633-.526 1.146-1.175 1.146H1.175C.526 16 0 15.487 0 14.854V1.146zm4.943 12.248V6.169H2.542v7.225h2.401zm-1.2-8.212c.837 0 1.358-.554 1.358-1.248-.015-.709-.52-1.248-1.342-1.248-.822 0-1.359.54-1.359 1.248 0 .694.521 1.248 1.327 1.248h.016zm4.908 8.212V9.359c0-.216.016-.432.08-.586.173-.431.568-.878 1.232-.878.869 0 1.216.662 1.216 1.634v3.865h2.401V9.25c0-2.22-1.184-3.252-2.764-3.252-1.274 0-1.845.7-2.165 1.193v.025h-.016a5.54 5.54 0 0 1 .016-.025V6.169h-2.4c.03.678 0 7.225 0 7.225h2.4z"/></svg></a>      
        </div>
    </section>
    
    <script>
        function myFunction() {
            /* Get the wallet address*/
            var address = "{{user_wallet.address}}";
            /* copy the address to clipbpard*/
            navigator.clipboard.writeText(address);
            /* Alert the copied text */
            alert("Address copied: " + address);
        }
    </script>                        
{% endblock content %}

wallet/templates/wallet/send_success.html
{% extends "wallet/base.html" %}
{% load humanize %}

{% block content %}
    <p> You have successfully sent {{amount}} BTC to {{recipient_address}} </p>
    
    <a href="{% url 'wallet:dashboard' %}"> Wallet DashBoard </a>

{% endblock content %}